Repository kubeedge/edgemesh, pull requests merged in 2021-08, with the labels that each got.

#29 docs: update readme for cross lan communicaiton feature
  README.md
  README_zh.md
  agent/pkg/chassis/protocol/tcp/handler.go
  build/agent/kubernetes/edgemesh-agent/04-daemonset.yaml
  build/agent/kubernetes/edgemesh-gateway/04-deployment.yaml
  build/server/edgemesh/06-deployment.yaml
  images/em-arch.png
Labels: lgtm, approved, size/L

#37 refactor edge gateway and transport http through tcp in feature cross lan communication
  agent/cmd/edgemesh-agent/app/server.go
  agent/pkg/chassis/registry/registry.go
  agent/pkg/gateway/controller/controller.go
  agent/pkg/proxy/proxy.go
  agent/pkg/tunnel/module.go
  agent/pkg/tunnel/tunnel.go
  build/agent/kubernetes/edgemesh-agent/03-configmap.yaml
  build/agent/kubernetes/edgemesh-gateway/03-configmap.yaml
Labels: lgtm, approved, size/M

#33 ci: add lint config
  .golangci.yml
  agent/cmd/edgemesh-agent/app/config/validation/validation.go
  agent/pkg/chassis/loadbalancer/consistenthash/hashring/cache.go
  agent/pkg/chassis/protocol/tcp/tcp.go
  agent/pkg/chassis/registry/registry.go
  agent/pkg/proxy/controller/controller.go
  agent/pkg/tunnel/protocol/tcp/tcpproxy.go
  common/constants/default.go
Labels: lgtm, approved, size/M

#45 fix missing strategy lock
  agent/pkg/chassis/loadbalancer/consistenthash/consistenthash.go
  agent/pkg/dns/module.go
  agent/pkg/tunnel/module.go
Labels: lgtm, approved, size/M

#56 when error, cannot print success logs
  server/pkg/tunnel/tunnel.go
Labels: lgtm, approved, size/XS

#54 fix possible agent_proxy resource leak
  agent/pkg/proxy/proxy.go
Labels: lgtm, approved, size/XS

#58 [#47]:bug:Bugfix:Secret cannot be updated when edgemesh-agent is started
  agent/cmd/edgemesh-agent/app/config/config.go
  build/agent/kubernetes/edgemesh-agent/03-configmap.yaml
  build/agent/kubernetes/edgemesh-gateway/03-configmap.yaml
  common/informers/informers.go
Labels: lgtm, approved, size/S

#53 fix gateway controller lock
  agent/pkg/gateway/controller/controller.go
Labels: lgtm, approved, size/XS

#57 Cross-edge-cloud features and yaml files
  README.md
  README_zh.md
  agent/pkg/chassis/config/config.go
  agent/pkg/proxy/config/config.go
  agent/pkg/proxy/iptables.go
  agent/pkg/proxy/module.go
  agent/pkg/proxy/protocol/protocol.go
  agent/pkg/proxy/proxy.go
  build/agent/kubernetes/edgemesh-agent/03-serviceaccount.yaml
  build/agent/kubernetes/edgemesh-agent/04-clusterrole.yaml
  build/agent/kubernetes/edgemesh-agent/05-clusterrolebinding.yaml
  build/agent/kubernetes/edgemesh-agent/06-configmap-cloud.yaml
  build/agent/kubernetes/edgemesh-agent/06-configmap-edge.yaml
  build/agent/kubernetes/edgemesh-agent/07-daemonset-cloud.yaml
  build/agent/kubernetes/edgemesh-agent/07-daemonset-edge.yaml
  build/agent/kubernetes/edgemesh-gateway/03-configmap.yaml
  build/agent/kubernetes/edgemesh-gateway/04-deployment.yaml
  build/server/edgemesh/05-configmap.yaml
  build/server/edgemesh/06-deployment.yaml
  examples/busybox.yaml
  examples/cloudzone.yaml
  examples/edgezone.yaml
  images/em-arch.png
  server/pkg/tunnel/controller/controller.go
Labels: lgtm, approved, size/XXL

#65 Update README.md
  README.md
Labels: lgtm, approved, size/XS

#63 bugfix: Failed to watch xxx: failed to list xxx net/http: TLS handshake timeout #59
  agent/pkg/proxy/iptables.go
Labels: lgtm, approved, size/M
