Repository kubeedge/edgemesh, pull requests merged in 2021-12, with the labels that each got.

#222 edgedns no longer writes nameserver to host's /etc/resolv.conf
  agent/pkg/dns/dns.go
  docs/.vuepress/config.ts
  docs/guide/getting-started.md
  docs/zh/guide/getting-started.md
Labels: lgtm, approved, size/L

#225 update test case document
  docs/.vuepress/config.ts
  docs/guide/getting-started.md
  docs/guide/test-case.md
  docs/zh/guide/getting-started.md
  docs/zh/guide/test-case.md
  examples/test-pod.yaml
Labels: lgtm, approved, size/L

#226 update doc about edged.clusterDomain config
  agent/cmd/edgemesh-agent/app/config/config.go
  docs/guide/getting-started.md
  docs/guide/test-case.md
  docs/zh/guide/getting-started.md
  docs/zh/guide/test-case.md
Labels: lgtm, approved, size/S

#228 docs: add edgemesh security proposal
  docs/proposal/edgemesh-security-proposal.md
  docs/proposal/images/edgemesh-security-sequence-uml.png
Labels: lgtm, approved, size/M

#231 docs: add edgemesh observability framework proposal
  docs/proposal/images/metrics-obsevability-framework.png
  docs/proposal/observability-support-proposal.md
Labels: lgtm, approved, size/M

#233 add https support and update docs
  README.md
  README_zh.md
  agent/pkg/proxy/proxy.go
  docs/guide/test-case.md
  docs/zh/guide/test-case.md
  examples/nginx-https/nginx.conf
  examples/nginx-https/nginx.yaml
  examples/nginx-https/tools.sh
  examples/test-pod.yaml
Labels: lgtm, approved, size/L

#238 delete the prerequisites part in the readme
  README.md
  README_zh.md
  docs/guide/test-case.md
  docs/zh/guide/test-case.md
Labels: lgtm, approved, size/S

#223 feature: support multi advertise address for edgemesh-server
  README.md
  README_zh.md
  build/helm/edgemesh.tgz
  build/helm/edgemesh/Chart.yaml
  build/helm/edgemesh/README.md
  build/helm/edgemesh/charts/agent/Chart.yaml
  build/helm/edgemesh/charts/server/Chart.yaml
  build/helm/edgemesh/charts/server/templates/04-configmap.yaml
  build/helm/edgemesh/charts/server/values.yaml
  build/server/edgemesh/05-configmap.yaml
  docs/advanced/architecture.md
  docs/guide/getting-started.md
  docs/proposal/edgemesh-security-proposal.md
  docs/proposal/observability-support-proposal.md
  docs/zh/advanced/architecture.md
  docs/zh/guide/getting-started.md
  server/pkg/tunnel/config/config.go
  server/pkg/tunnel/module.go
Labels: lgtm, approved, size/L

#243 docs: fix format error for edgemesh website
  docs/guide/getting-started.md
  docs/zh/guide/getting-started.md
Labels: lgtm, approved, size/S

#242 add a socks5 proxy
  agent/pkg/proxy/config/config.go
  agent/pkg/proxy/module.go
  agent/pkg/proxy/proxy.go
  agent/pkg/proxy/socks5_proxy.go
Labels: lgtm, approved, size/L

#246 add document of socks5proxy and configuration of socks5proxy
  build/agent/kubernetes/edgemesh-agent/05-configmap.yaml
  build/helm/edgemesh.tgz
  build/helm/edgemesh/charts/agent/templates/04-configmap.yaml
  build/helm/edgemesh/charts/agent/values.yaml
  docs/.vuepress/configs/sidebar/en.ts
  docs/.vuepress/configs/sidebar/zh.ts
  docs/.vuepress/public/images/guide/em-sock5.png
  docs/guide/ssh.md
  docs/zh/guide/ssh.md
Labels: lgtm, approved, size/L

#248 modifying documents and synchronizing host time for container
  build/agent/kubernetes/edgemesh-agent/06-daemonset.yaml
  build/agent/kubernetes/edgemesh-gateway/03-deployment.yaml
  build/helm/edgemesh-gateway.tgz
  build/helm/edgemesh.tgz
  build/helm/edgemesh/charts/agent/templates/05-daemonset.yaml
  build/helm/edgemesh/charts/server/templates/05-deployment.yaml
  build/helm/gateway/templates/05-deployment.yaml
  build/server/edgemesh/06-deployment.yaml
  docs/guide/edge-gateway.md
  docs/guide/ssh.md
  docs/zh/guide/edge-gateway.md
  docs/zh/guide/ssh.md
Labels: lgtm, approved, size/M

#249 add edgemesh config items document
  README.md
  README_zh.md
  docs/.vuepress/configs/sidebar/en.ts
  docs/.vuepress/configs/sidebar/zh.ts
  docs/guide/README.md
  docs/guide/ssh.md
  docs/reference/config-items.md
  docs/zh/guide/README.md
  docs/zh/guide/ssh.md
  docs/zh/reference/config-items.md
Labels: lgtm, approved, size/XL

#250 edgemesh-gateway supports deployment on the cloud node
  agent/pkg/dns/corefile.go
  build/agent/kubernetes/edgemesh-gateway/02-serviceaccount.yaml
  build/agent/kubernetes/edgemesh-gateway/03-clusterrole.yaml
  build/agent/kubernetes/edgemesh-gateway/04-clusterrolebinding.yaml
  build/agent/kubernetes/edgemesh-gateway/05-configmap.yaml
  build/agent/kubernetes/edgemesh-gateway/06-deployment.yaml
  build/helm/edgemesh-gateway.tgz
  build/helm/gateway/Chart.yaml
  docs/guide/edge-gateway.md
  docs/zh/guide/edge-gateway.md
Labels: lgtm, approved, size/M

#253 support access to external services through custom endpoints and services
  agent/pkg/chassis/protocol/tcp/handler.go
  agent/pkg/chassis/registry/registry.go
Labels: lgtm, approved, size/M

#251 refactor: refactor security config field
  agent/pkg/tunnel/config/config.go
  agent/pkg/tunnel/module.go
  build/helm/edgemesh-gateway.tgz
  build/helm/edgemesh.tgz
  build/helm/edgemesh/charts/agent/templates/04-configmap.yaml
  build/helm/edgemesh/charts/agent/templates/05-daemonset.yaml
  build/helm/edgemesh/charts/agent/values.yaml
  build/helm/edgemesh/charts/server/templates/04-configmap.yaml
  build/helm/edgemesh/charts/server/templates/05-deployment.yaml
  build/helm/edgemesh/charts/server/values.yaml
  build/helm/gateway/templates/04-configmap.yaml
  build/helm/gateway/templates/05-deployment.yaml
  build/helm/gateway/values.yaml
  common/security/camanager.go
  common/security/config.go
  common/security/manager.go
  common/security/nocamanager.go
  docs/.vuepress/configs/navbar/en.ts
  docs/.vuepress/configs/navbar/zh.ts
  docs/.vuepress/configs/sidebar/en.ts
  docs/.vuepress/configs/sidebar/zh.ts
  docs/guide/security.md
  docs/reference/config-items.md
  docs/zh/guide/security.md
  docs/zh/reference/config-items.md
  server/pkg/tunnel/config/config.go
  server/pkg/tunnel/module.go
Labels: lgtm, approved, size/L

#254 the Socks5Proxy field of EdgeProxyConfig is modified to a pointer type
  agent/pkg/proxy/config/config.go
Labels: lgtm, approved, size/XS

#255 feature: support liveness probe
  build/agent/kubernetes/edgemesh-agent/06-daemonset.yaml
  build/agent/kubernetes/edgemesh-gateway/06-deployment.yaml
  build/helm/edgemesh-gateway.tgz
  build/helm/edgemesh.tgz
  build/helm/edgemesh/charts/agent/templates/05-daemonset.yaml
  build/helm/edgemesh/charts/agent/values.yaml
  build/helm/edgemesh/charts/server/templates/05-deployment.yaml
  build/helm/edgemesh/charts/server/values.yaml
  build/helm/gateway/templates/05-deployment.yaml
  build/helm/gateway/values.yaml
  build/server/edgemesh/06-deployment.yaml
Labels: lgtm, approved, size/M

#256 update document and deleted the useless 01-namespace.yaml
  build/agent/kubernetes/edgemesh-agent/01-namespace.yaml
  build/agent/kubernetes/edgemesh-agent/01-serviceaccount.yaml
  build/agent/kubernetes/edgemesh-agent/02-clusterrole.yaml
  build/agent/kubernetes/edgemesh-agent/03-clusterrolebinding.yaml
  build/agent/kubernetes/edgemesh-agent/04-configmap.yaml
  build/agent/kubernetes/edgemesh-agent/05-configmap.yaml
  build/agent/kubernetes/edgemesh-agent/05-daemonset.yaml
  build/agent/kubernetes/edgemesh-gateway/01-namespace.yaml
  build/agent/kubernetes/edgemesh-gateway/01-serviceaccount.yaml
  build/agent/kubernetes/edgemesh-gateway/02-clusterrole.yaml
  build/agent/kubernetes/edgemesh-gateway/03-clusterrolebinding.yaml
  build/agent/kubernetes/edgemesh-gateway/04-configmap.yaml
  build/agent/kubernetes/edgemesh-gateway/05-configmap.yaml
  build/agent/kubernetes/edgemesh-gateway/05-deployment.yaml
  build/helm/edgemesh-gateway.tgz
  build/helm/edgemesh.tgz
  build/helm/edgemesh/charts/agent/templates/02-clusterrole.yaml
  build/helm/edgemesh/charts/agent/values.yaml
  build/helm/edgemesh/charts/server/templates/04-configmap.yaml
  build/helm/edgemesh/charts/server/values.yaml
  build/helm/gateway/templates/02-clusterrole.yaml
  build/server/edgemesh/01-namespace.yaml
  build/server/edgemesh/01-serviceaccount.yaml
  build/server/edgemesh/02-clusterrole.yaml
  build/server/edgemesh/03-clusterrolebinding.yaml
  build/server/edgemesh/04-configmap.yaml
  build/server/edgemesh/05-configmap.yaml
  build/server/edgemesh/05-deployment.yaml
  docs/.vuepress/configs/sidebar/en.ts
  docs/guide/edge-gateway.md
  docs/guide/getting-started.md
  docs/guide/security.md
  docs/guide/ssh.md
  docs/reference/config-items.md
  docs/zh/guide/edge-gateway.md
  docs/zh/guide/getting-started.md
  docs/zh/guide/security.md
  docs/zh/guide/ssh.md
  docs/zh/reference/config-items.md
Labels: lgtm, approved, size/L

#257 fix addr.TargetRef is nil problem
  agent/pkg/chassis/controller/controller.go
  agent/pkg/chassis/registry/registry.go
  docs/guide/security.md
  docs/reference/config-items.md
  docs/zh/reference/config-items.md
Labels: lgtm, approved, size/M

#259 use make in dockerfile to build executable file
  agent/pkg/chassis/controller/controller.go
  agent/pkg/chassis/registry/registry.go
  build/agent/Dockerfile
  build/server/Dockerfile
  hack/lib/buildx.sh
  hack/lib/init.sh
Labels: lgtm, approved, size/S

#258 add proposal of socks5proxy
  docs/proposal/edgemesh-ssh-proposal.md
  docs/proposal/images/edgemesh-ssh-workflow.png
Labels: lgtm, approved, size/S

#260 test image is replaced with poorunga/serve_hostname
  examples/hostname-lb-consistenthash.yaml
  examples/hostname-lb-default.yaml
  examples/hostname-lb-random-gateway-route.yaml
  examples/hostname-lb-random-gateway-tls.yaml
  examples/hostname-lb-random-gateway.yaml
  examples/hostname-lb-random.yaml
  examples/hostname-lb-roundrobin.yaml
  examples/hostname.yaml
Labels: lgtm, approved, size/S

#261 websocket test image is replaced with poorunga/websocket_echo
  docs/guide/test-case.md
  docs/zh/guide/test-case.md
  examples/test-pod.yaml
  examples/websocket.yaml
Labels: lgtm, approved, size/S

#263 tcp test image is replaced with poorunga/go-echo
  examples/cloudzone.yaml
  examples/edgezone.yaml
  examples/tcp-echo-service.yaml
Labels: lgtm, approved, size/XS

#264 edgemesh-agent support turn off hole punching option
  agent/pkg/tunnel/config/config.go
  agent/pkg/tunnel/module.go
  build/helm/edgemesh-gateway.tgz
  build/helm/edgemesh.tgz
  build/helm/edgemesh/charts/agent/templates/04-configmap.yaml
  build/helm/edgemesh/charts/agent/values.yaml
  build/helm/gateway/templates/04-configmap.yaml
  build/helm/gateway/values.yaml
  docs/reference/config-items.md
  docs/zh/reference/config-items.md
Labels: lgtm, approved, size/M

#265 Edgemesh helm ci && combine sub charts of edgemesh
  .github/workflows/release-helm-package.yaml
  build/helm/edgemesh/Chart.yaml
  build/helm/edgemesh/README.md
  build/helm/edgemesh/charts/agent/Chart.yaml
  build/helm/edgemesh/charts/agent/templates/05-daemonset.yaml
  build/helm/edgemesh/charts/agent/values.yaml
  build/helm/edgemesh/charts/server/templates/05-deployment.yaml
  build/helm/edgemesh/charts/server/values.yaml
  build/helm/edgemesh/values.yaml
  build/helm/gateway/README.md
  build/helm/gateway/templates/05-deployment.yaml
  build/helm/gateway/values.yaml
  hack/update-helm-package.sh
Labels: lgtm, approved, size/L

#266 Add logic for verifying helm packages
  .github/workflows/main.yaml
  build/helm/edgemesh-gateway.tgz
  build/helm/edgemesh.tgz
  hack/update-helm-package.sh
  hack/verify-helm-package.sh
Labels: lgtm, approved, size/M

#267 refactor: use helm install edgemesh in ci
  .github/workflows/main.yaml
  build/helm/edgemesh-gateway.tgz
  build/helm/edgemesh.tgz
  build/helm/edgemesh/charts/agent/templates/05-daemonset.yaml
  build/helm/edgemesh/values.yaml
  hack/local-up-edgemesh.sh
Labels: lgtm, approved, size/L

#268 refactor: use action step to setup helm
  .github/workflows/main.yaml
Labels: lgtm, approved, size/S
