Repository kubeedge/edgemesh, pull requests merged in 2021-11, with the labels that each got.

#156 simplify the content of the README
  README.md
  README_zh.md
  docs/.vuepress/public/images/advanced/future-work.png
  docs/advanced/architecture.md
  docs/guide/README.md
  docs/guide/test-case.md
  docs/zh/advanced/architecture.md
  docs/zh/guide/README.md
  docs/zh/guide/test-case.md
  images/bell-outline-badge.svg
  images/em-arch.png
  images/em-ig.png
  images/em-principle.png
Labels: lgtm, approved, size/XXL

#157 fix some docs issue
  build/agent/kubernetes/edgemesh-gateway/03-deployment.yaml
  docs/guide/edge-gateway.md
  docs/guide/getting-started.md
  docs/guide/test-case.md
  docs/zh/guide/edge-gateway.md
  docs/zh/guide/getting-started.md
  docs/zh/guide/test-case.md
  examples/cloudzone.yaml
  examples/edgezone.yaml
  examples/hostname.yaml
Labels: lgtm, approved, size/M

#158 change all examples resource namespace from edgemesh-test to default
  README.md
  docs/guide/edge-gateway.md
  docs/guide/test-case.md
  docs/zh/guide/edge-gateway.md
  docs/zh/guide/test-case.md
  examples/busybox.yaml
  examples/cloudzone.yaml
  examples/edgezone.yaml
  examples/hostname-lb-consistenthash.yaml
  examples/hostname-lb-default.yaml
  examples/hostname-lb-random-gateway-route.yaml
  examples/hostname-lb-random-gateway-tls.yaml
  examples/hostname-lb-random-gateway.yaml
  examples/hostname-lb-random.yaml
  examples/hostname-lb-roundrobin.yaml
  examples/hostname.yaml
  examples/tcp-echo-service.yaml
  examples/websocket.yaml
Labels: lgtm, approved, size/XL

#159 add EdgeMesh's helm installation method
  build/helm/edgemesh/charts/server/values.yaml
  docs/guide/getting-started.md
  docs/zh/guide/getting-started.md
Labels: lgtm, approved, size/L

#161 modify user guide
  docs/guide/getting-started.md
  docs/zh/guide/getting-started.md
Labels: lgtm, approved, size/XS

#160 ci: improve e2e code
  tests/e2e/k8s/tools.go
  tests/e2e/traffic/testsuite.go
  tests/e2e/traffic/traffic_test.go
Labels: lgtm, approved, size/XS

#113 support traffic governance using HTTP
  agent/pkg/chassis/protocol/http/http.go
  agent/pkg/chassis/protocol/tcp/handler.go
  agent/pkg/chassis/protocol/tcp/tcp.go
  agent/pkg/gateway/controller/controller.go
  agent/pkg/proxy/proxy.go
Labels: kind/bug, lgtm, approved, size/L

#164 modified netif code, use bridge device instead of dummy device
  LICENSES/vendor/k8s.io/dns/LICENSE
  agent/cmd/edgemesh-agent/app/server.go
  common/util/netif.go
  go.mod
  go.sum
  vendor/k8s.io/dns/LICENSE
  vendor/k8s.io/dns/pkg/netif/netif.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#165 update edgemesh helm installation
  build/helm/edgemesh.tgz
  docs/guide/getting-started.md
  docs/guide/test-case.md
  docs/zh/guide/getting-started.md
  docs/zh/guide/test-case.md
Labels: lgtm, approved, size/M

#167 change List-Watch to Local APIServer
  README.md
  README_zh.md
  agent/cmd/edgemesh-agent/app/server.go
  docs/advanced/architecture.md
  docs/guide/getting-started.md
  docs/zh/advanced/architecture.md
  docs/zh/guide/getting-started.md
  hack/local-up-edgemesh.sh
Labels: lgtm, approved, size/M

#171 use const instead the magic number
  agent/pkg/proxy/protocol/protocol.go
Labels: lgtm, approved, size/S

#178 fix dns domain resolve bug
  agent/pkg/dns/dns.go
Labels: lgtm, approved, size/XS

#174 improve: add error message
  agent/pkg/tunnel/tunnel.go
Labels: lgtm, approved, size/XS

#175 fix edgemesh-agent proxy fetching protocol bug
  agent/pkg/chassis/protocol/http/http.go
  agent/pkg/chassis/protocol/protocol.go
  agent/pkg/chassis/protocol/tcp/tcp.go
  agent/pkg/chassis/registry/registry.go
  agent/pkg/proxy/controller/controller.go
  agent/pkg/proxy/iptables.go
Labels: lgtm, approved, size/M

#183 fixed an issue where dns resolution returned incorrect default namespace
  agent/pkg/chassis/loadbalancer/consistenthash/consistenthash.go
  agent/pkg/chassis/protocol/http/http.go
  agent/pkg/dns/dns.go
  agent/pkg/tunnel/module.go
  common/util/util.go
Labels: lgtm, approved, size/M

#184 support push docker images for multi architectures
  Makefile
  hack/lib/buildx.sh
  hack/make-rules/push.sh
Labels: lgtm, approved, size/M

#186 support consistentHash when pods distributed in different nodes in same podIP
  agent/pkg/chassis/controller/controller.go
  agent/pkg/chassis/loadbalancer/consistenthash/hashring/serviceinstance.go
  agent/pkg/chassis/registry/registry.go
Labels: kind/bug, lgtm, approved, size/S

#191 delete duplicate function "GetStrategyName"
  agent/pkg/chassis/protocol/util/strategy.go
Labels: lgtm, approved, size/M

#190 add lock while deleting hash ring
  agent/pkg/chassis/controller/controller.go
Labels: lgtm, approved, size/S

#193 use const instead the string
  common/util/util.go
Labels: lgtm, approved, size/XS

#195 avoid edgemesh-server'addrs list have repeated ip
  server/pkg/tunnel/module.go
Labels: lgtm, approved, size/S

#196 fix wrong annotation of map ipBySvc
  agent/pkg/proxy/controller/controller.go
Labels: lgtm, approved, size/XS

#199 change docker cross build platform type
  hack/lib/buildx.sh
Labels: lgtm, approved, size/XS

#197 fix some errors for fmt.Errorf-statements
  agent/pkg/tunnel/protocol/tcp/tcpproxy.go
Labels: lgtm, approved, size/XS

#202 delete unnecessary sort of microServiceInstances
  agent/pkg/chassis/registry/registry.go
Labels: lgtm, approved, size/XS

#203 If kubeAPIConfig is configured, the value prefer to user’s
  agent/cmd/edgemesh-agent/app/config/config.go
  agent/cmd/edgemesh-agent/app/server.go
  build/agent/kubernetes/edgemesh-agent/05-configmap.yaml
  build/agent/kubernetes/edgemesh-gateway/02-configmap.yaml
  build/helm/edgemesh/charts/agent/values.yaml
  build/helm/gateway/values.yaml
Labels: lgtm, approved, size/L

#206 fix some default value
  agent/pkg/dns/config/config.go
  agent/pkg/gateway/config/config.go
  agent/pkg/proxy/config/config.go
  agent/pkg/tunnel/config/config.go
Labels: lgtm, approved, size/S

#207 remove unused value
  agent/pkg/chassis/registry/registry.go
  agent/pkg/tunnel/module.go
  agent/pkg/tunnel/tunnel.go
Labels: lgtm, approved, size/XS

#208 edgedns in the configuration file is configured as the highest authority
  agent/cmd/edgemesh-agent/app/config/config.go
  agent/cmd/edgemesh-agent/app/server.go
  build/agent/kubernetes/edgemesh-agent/05-configmap.yaml
  build/helm/edgemesh.tgz
  build/helm/edgemesh/charts/agent/templates/04-configmap.yaml
  build/helm/edgemesh/charts/agent/values.yaml
  build/helm/gateway/templates/04-configmap.yaml
  build/helm/gateway/values.yaml
Labels: lgtm, approved, size/M

#210 use constant for edge ApiServer
  agent/cmd/edgemesh-agent/app/config/config.go
Labels: lgtm, approved, size/XS

#209 replace klog.Fatal with klog.Exit
  server/cmd/edgemesh-server/app/server.go
Labels: lgtm, approved, size/XS

#212 docs: update the cloudcore restart command
  docs/guide/getting-started.md
  docs/zh/guide/getting-started.md
Labels: lgtm, approved, size/XS

#213 consistentHash uses http header parsing uniformly
  agent/pkg/chassis/loadbalancer/consistenthash/consistenthash.go
Labels: lgtm, approved, size/L

#214 adjust the gateway directory to fit virtualService
  agent/pkg/gateway/controller/controller.go
  agent/pkg/gateway/manager/manager.go
  agent/pkg/gateway/manager/server.go
  agent/pkg/gateway/manager/tls.go
  agent/pkg/gateway/module.go
Labels: lgtm, approved, size/XL

#217 Grammar fix in proxy module
  agent/pkg/proxy/iptables.go
  agent/pkg/proxy/proxy.go
Labels: kind/feature, lgtm, approved, size/XS

#211 remove '0.0.0.0' for publicIP
  server/pkg/tunnel/config/config.go
Labels: lgtm, approved, size/XS

#218 Fix log's capitalization in tunnel module
  agent/pkg/tunnel/controller/controller.go
  agent/pkg/tunnel/protocol/tcp/tcpproxy.go
Labels: lgtm, approved, size/S

#219 remove GetPodsSelector
  common/util/util.go
Labels: lgtm, approved, size/S

#216 when print defaultConfig no longer read from env，and get nodeName from env only once
  agent/pkg/chassis/config/config.go
  agent/pkg/chassis/install.go
  agent/pkg/tunnel/config/config.go
  agent/pkg/tunnel/module.go
  common/acl/camanager.go
  common/util/util.go
  server/pkg/tunnel/config/config.go
  server/pkg/tunnel/module.go
Labels: lgtm, approved, size/M
