Repository kubeedge/edgemesh, pull requests merged in 2021-09, with the labels that each got.

#66 validate the kube-dns is nil AND add ignore rules from coredns
  agent/pkg/proxy/iptables.go
  go.sum
Labels: lgtm, approved, size/S

#70 Added a label: proxyby=edgemesh for services that require cloud-side communication.
  agent/pkg/proxy/iptables.go
Labels: kind/bug, lgtm, approved, size/L

#72 When refreshing iptables, solve the interruption risk of communication services
  LICENSES/vendor/github.com/thoas/go-funk/LICENSE
  agent/pkg/proxy/iptables.go
  go.mod
  go.sum
  hack/verify-vendor.sh
  vendor/github.com/thoas/go-funk/.gitignore
  vendor/github.com/thoas/go-funk/.travis.yml
  vendor/github.com/thoas/go-funk/CHANGELOG.md
  vendor/github.com/thoas/go-funk/LICENSE
  vendor/github.com/thoas/go-funk/Makefile
  vendor/github.com/thoas/go-funk/README.rst
  vendor/github.com/thoas/go-funk/assign.go
  vendor/github.com/thoas/go-funk/builder.go
  vendor/github.com/thoas/go-funk/chain_builder.go
  vendor/github.com/thoas/go-funk/compact.go
  vendor/github.com/thoas/go-funk/fill.go
  vendor/github.com/thoas/go-funk/go.mod
  vendor/github.com/thoas/go-funk/go.sum
  vendor/github.com/thoas/go-funk/helpers.go
  vendor/github.com/thoas/go-funk/intersection.go
  vendor/github.com/thoas/go-funk/join.go
  vendor/github.com/thoas/go-funk/join_primitives.go
  vendor/github.com/thoas/go-funk/lazy_builder.go
  vendor/github.com/thoas/go-funk/map.go
  vendor/github.com/thoas/go-funk/max.go
  vendor/github.com/thoas/go-funk/min.go
  vendor/github.com/thoas/go-funk/operation.go
  vendor/github.com/thoas/go-funk/options.go
  vendor/github.com/thoas/go-funk/permutation.go
  vendor/github.com/thoas/go-funk/predicate.go
  vendor/github.com/thoas/go-funk/presence.go
  vendor/github.com/thoas/go-funk/reduce.go
  vendor/github.com/thoas/go-funk/retrieve.go
  vendor/github.com/thoas/go-funk/scan.go
  vendor/github.com/thoas/go-funk/short_if.go
  vendor/github.com/thoas/go-funk/subset.go
  vendor/github.com/thoas/go-funk/subtraction.go
  vendor/github.com/thoas/go-funk/transform.go
  vendor/github.com/thoas/go-funk/typesafe.go
  vendor/github.com/thoas/go-funk/utils.go
  vendor/github.com/thoas/go-funk/without.go
  vendor/github.com/thoas/go-funk/zip.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, size/XXL

#83 :book:init edgemesh doc
  .github/workflows/docs.yml
  .gitignore
  docs/.vuepress/config.ts
  docs/.vuepress/configs/index.ts
  docs/.vuepress/configs/navbar/en.ts
  docs/.vuepress/configs/navbar/index.ts
  docs/.vuepress/configs/navbar/zh.ts
  docs/.vuepress/configs/sidebar/en.ts
  docs/.vuepress/configs/sidebar/index.ts
  docs/.vuepress/configs/sidebar/zh.ts
  docs/.vuepress/public/images/advanced/em-arch.png
  docs/.vuepress/public/images/guide/em-ig.png
  docs/.vuepress/public/images/hero.png
  docs/.vuepress/public/images/icons/favicon.png
  docs/.vuepress/styles/index.scss
  docs/OWNERS
  docs/README.md
  docs/advanced/architecture.md
  docs/guide/README.md
  docs/guide/edge-gateway.md
  docs/guide/getting-started.md
  docs/guide/test-case.md
  docs/zh/README.md
  docs/zh/advanced/architecture.md
  docs/zh/guide/README.md
  docs/zh/guide/edge-gateway.md
  docs/zh/guide/getting-started.md
  docs/zh/guide/test-case.md
  package.json
  yarn.lock
Labels: lgtm, approved, size/XXL

#81 fix handle l4 proxy err
  agent/pkg/chassis/registry/registry.go
Labels: lgtm, approved, size/XS

#86 docs: add contributing and developer guide files
  CONTRIBUTING.md
  README.md
  README_zh.md
  docs/contribute/contributing-guide.md
  docs/contribute/developer-guide.md
Labels: lgtm, approved, size/L

#96 add edgemesh owners
  OWNERS
Labels: lgtm, approved, size/XS

#88 Add the edgemesh + kube-proxy hybird deploy simple docs
  docs/.vuepress/configs/navbar/en.ts
  docs/.vuepress/configs/navbar/zh.ts
  docs/.vuepress/configs/sidebar/en.ts
  docs/.vuepress/configs/sidebar/zh.ts
  docs/advanced/hybirdnat.md
  docs/zh/advanced/hybirdnat.md
Labels: lgtm, approved, size/L
