Repository kubeedge/edgemesh, pull requests merged in 2022-10, with the labels that each got.

#384 add Edge Kube-API Endpoint document
  docs/.vuepress/configs/sidebar/en.ts
  docs/.vuepress/configs/sidebar/zh.ts
  docs/guide/README.md
  docs/guide/edge-kube-api.md
  docs/reference/config-items.md
  docs/zh/guide/README.md
  docs/zh/guide/edge-kube-api.md
  docs/zh/reference/config-items.md
Labels: size/XL

#385 update docs: service filtering to service filter
  docs/advanced/hybird-proxy.md
  docs/guide/README.md
  docs/zh/guide/README.md
Labels: lgtm, approved, size/XS

#390 feat: added ServiceFilterMode option for proxy
  build/helm/edgemesh.tgz
  build/helm/edgemesh/charts/agent/templates/04-configmap.yaml
  docs/advanced/hybird-proxy.md
  docs/reference/config-items.md
  pkg/apis/config/defaults/default.go
  pkg/apis/config/v1alpha1/default.go
  pkg/apis/config/v1alpha1/types.go
  pkg/apis/config/v1alpha1/validation/validation.go
  pkg/proxy/module.go
  pkg/proxy/server.go
Labels: lgtm, approved, size/M

#397 fix broken link in docs
  docs/guide/README.md
  docs/zh/guide/README.md
Labels: lgtm, approved, size/S
