Repository kubeedge/edgemesh, pull requests merged in 2022-12, with the labels that each got.

#407 http gateway verifies the compliance of the request's host
  hack/local-up-edgemesh.sh
  pkg/gateway/http.go
  pkg/gateway/http_test.go
  pkg/gateway/protocol.go
  pkg/gateway/protocol_test.go
  pkg/gateway/tcp.go
Labels: size/XL

#408 add ha docs sidebar
  docs/.vuepress/configs/sidebar/en.ts
  docs/.vuepress/configs/sidebar/zh.ts
Labels: size/XS

#409 fix not found link
  README.md
  README_zh.md
Labels: lgtm, approved, size/XS
