Repository kubeedge/edgemesh, pull requests merged in 2022-02, with the labels that each got.

#284 remove extra spaces
  hack/local-up-edgemesh.sh
Labels: lgtm, approved, size/XS

#285 remove extra indentation
  build/agent/kubernetes/edgemesh-agent/05-daemonset.yaml
  build/server/edgemesh/05-deployment.yaml
Labels: lgtm, approved, size/L

#287 update go-libp2p-tls version to fix quic tls connect problem
  agent/pkg/tunnel/module.go
  agent/pkg/tunnel/proxy/proxy.go
  go.mod
  go.sum
  server/pkg/tunnel/module.go
  vendor/github.com/libp2p/go-libp2p-tls/crypto.go
  vendor/github.com/libp2p/go-libp2p-tls/go.mod
  vendor/github.com/libp2p/go-libp2p-tls/hook_ca.go
  vendor/github.com/libp2p/go-libp2p-tls/hook_ecdsa.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#299 add udp proxy retry sleep time
  agent/pkg/tunnel/proxy/proxy.go
Labels: lgtm, approved, size/XS

#300 add sleep time in get proxy stream
  third_party/forked/kubernetes/pkg/proxy/userspace/proxysocket.go
Labels: lgtm, approved, size/XS

#301 fixed edgemesh-server assisting hole punching failure
  LICENSES/vendor/github.com/libp2p/go-libp2p-circuit/LICENSE
  go.mod
  server/pkg/tunnel/module.go
  vendor/github.com/libp2p/go-libp2p-circuit/.travis.yml
  vendor/github.com/libp2p/go-libp2p-circuit/LICENSE
  vendor/github.com/libp2p/go-libp2p-circuit/README.md
  vendor/github.com/libp2p/go-libp2p-circuit/codecov.yml
  vendor/github.com/libp2p/go-libp2p-circuit/conn.go
  vendor/github.com/libp2p/go-libp2p-circuit/dial.go
  vendor/github.com/libp2p/go-libp2p-circuit/go.mod
  vendor/github.com/libp2p/go-libp2p-circuit/go.sum
  vendor/github.com/libp2p/go-libp2p-circuit/listen.go
  vendor/github.com/libp2p/go-libp2p-circuit/pb/Makefile
  vendor/github.com/libp2p/go-libp2p-circuit/pb/relay.pb.go
  vendor/github.com/libp2p/go-libp2p-circuit/pb/relay.proto
  vendor/github.com/libp2p/go-libp2p-circuit/relay.go
  vendor/github.com/libp2p/go-libp2p-circuit/transport.go
  vendor/github.com/libp2p/go-libp2p-circuit/util.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#302 update enableHolePunch document and helm charts
  build/helm/edgemesh-gateway.tgz
  build/helm/edgemesh.tgz
  build/helm/edgemesh/values.yaml
  docs/reference/config-items.md
  docs/zh/reference/config-items.md
Labels: lgtm, approved, size/XS

#303 optimize NewManager function
  common/security/manager.go
Labels: lgtm, approved, size/S

#304 unify the format string of legacy and libp2p dial
  third_party/forked/kubernetes/pkg/proxy/userspace/proxysocket.go
Labels: lgtm, approved, size/M

#306 add udp demo in docs and update readme
  README.md
  README_zh.md
  docs/guide/test-case.md
  docs/zh/guide/test-case.md
  examples/hostname-udp.yaml
Labels: lgtm, approved, size/L

#307 modify the labels of services filtered by edgemesh
  docs/advanced/hybirdnat.md
  docs/guide/README.md
  docs/zh/advanced/hybirdnat.md
  docs/zh/guide/README.md
Labels: lgtm, approved, size/L

#308 modify getting-started.md
  docs/guide/getting-started.md
  docs/zh/guide/getting-started.md
Labels: lgtm, approved, size/L

#309 add edgemesh loadbalance test
  Makefile
  tests/loadbalance/README.md
  tests/loadbalance/execute.sh
  tests/loadbalance/hostname-deploy.yaml
  tests/loadbalance/hostname-dr-random.yaml
  tests/loadbalance/hostname-svc.yaml
  tests/loadbalance/kube.go
  tests/loadbalance/loadbalance.go
Labels: lgtm, approved, size/L

#311 add cachedns document and helm charts
  build/helm/edgemesh-gateway.tgz
  build/helm/edgemesh.tgz
  build/helm/edgemesh/charts/agent/templates/04-configmap.yaml
  build/helm/edgemesh/charts/agent/values.yaml
  build/helm/edgemesh/values.yaml
  build/helm/gateway/templates/04-configmap.yaml
  build/helm/gateway/values.yaml
  docs/reference/config-items.md
  docs/zh/reference/config-items.md
Labels: lgtm, approved, size/L
