Repository kubeedge/edgemesh, pull requests merged in 2022-03, with the labels that each got.

#313 test cachedns in ci
  hack/local-up-edgemesh.sh
Labels: lgtm, approved, size/S

#315 libp2p.NetworkStream as an implementation of net.Conn
  agent/pkg/chassis/protocol/tcp/handler.go
  agent/pkg/proxy/socks5_proxy.go
  agent/pkg/tunnel/module.go
  agent/pkg/tunnel/proxy/proxy.go
  common/libp2p/types.go
  common/util/proxy.go
  third_party/forked/kubernetes/pkg/proxy/userspace/proxysocket.go
Labels: lgtm, approved, size/L

#316 add ability to detect iptables mode in edgemesh-agent image
  build/agent/Dockerfile
  build/agent/iptables-wrapper
Labels: lgtm, approved, size/M

#319 add resources config in helm charts
  build/helm/edgemesh-gateway.tgz
  build/helm/edgemesh.tgz
  build/helm/edgemesh/charts/agent/templates/05-daemonset.yaml
  build/helm/edgemesh/charts/server/templates/05-deployment.yaml
  build/helm/edgemesh/charts/server/values.yaml
  build/helm/edgemesh/values.yaml
  build/helm/gateway/templates/05-deployment.yaml
  build/helm/gateway/values.yaml
Labels: lgtm, approved, size/M

#322 add empty value in server.advertiseAddress
  build/helm/edgemesh-gateway.tgz
  build/helm/edgemesh.tgz
  build/helm/edgemesh/Chart.yaml
  build/helm/edgemesh/charts/server/values.yaml
  build/helm/edgemesh/values.yaml
Labels: lgtm, approved, size/XS

#324 Remove the code that closes defer rconn.Close()
  agent/pkg/chassis/protocol/tcp/handler.go
Labels: lgtm, approved, size/XS

#326 no need to run informers in manager
  agent/pkg/chassis/controller/controller.go
  agent/pkg/gateway/controller/controller.go
  agent/pkg/tunnel/controller/controller.go
  common/informers/informers.go
  server/pkg/tunnel/controller/controller.go
Labels: lgtm, approved, size/S

#333 update match label in cloudzone and edgezone examples
  examples/cloudzone.yaml
  examples/edgezone.yaml
Labels: lgtm, approved, size/S

#334 fix err return value is always empty
  agent/pkg/tunnel/proxy/proxy.go
Labels: size/S

#331 use const instead the string
  agent/pkg/dns/corefile.go
Labels: lgtm, approved, size/XS
