Repository kubeedge/edgemesh, pull requests merged in 2022-04, with the labels that each got.

#337 use camel case instead of snake case
  common/constants/default.go
  common/util/util.go
Labels: lgtm, approved, size/XS

#341 change imagePullPolicy to IfNotPresent
  build/agent/kubernetes/edgemesh-agent/05-daemonset.yaml
  build/agent/kubernetes/edgemesh-gateway/05-deployment.yaml
  examples/cloudzone.yaml
  examples/edgezone.yaml
  examples/tcp-echo-service.yaml
Labels: lgtm, approved, size/XS

#342 fix-328: ssh_exchange_identification: Connection closed by remote host
  agent/pkg/proxy/socks5_proxy.go
Labels: lgtm, approved, size/XS

#347 fix hashKey in proxy loadbalancer when key type is UserSourceIP
  third_party/forked/kubernetes/pkg/proxy/userspace/loadbalancer_ex.go
  third_party/forked/kubernetes/pkg/proxy/userspace/loadbalancer_strategy.go
Labels: lgtm, approved, size/M

#348 pick a correct endpoint when there are more than one port in a service and strategy is consistent hash
  third_party/forked/kubernetes/pkg/proxy/userspace/loadbalancer.go
  third_party/forked/kubernetes/pkg/proxy/userspace/loadbalancer_ex.go
  third_party/forked/kubernetes/pkg/proxy/userspace/loadbalancer_ex_test.go
  third_party/forked/kubernetes/pkg/proxy/userspace/loadbalancer_strategy.go
  third_party/forked/kubernetes/pkg/proxy/userspace/proxysocket.go
Labels: lgtm, approved, size/L
