Repository kubeedge/edgemesh, pull requests merged in 2022-01, with the labels that each got.

#269 docs: change setup link to correct url
  docs/contribute/contributing-guide.md
Labels: lgtm, approved, size/XS

#270 Change the format of nodeName so that users can expose errors when th…
  build/agent/kubernetes/edgemesh-gateway/05-deployment.yaml
  build/server/edgemesh/05-deployment.yaml
Labels: lgtm, approved, size/XS

#271 Modify some document expression
  docs/guide/getting-started.md
  docs/zh/guide/getting-started.md
Labels: lgtm, approved, size/XS

#272 make ticker goroutine stop
  agent/pkg/proxy/iptables.go
Labels: lgtm, approved, size/XS

#273 handle dns.UpdateCorefile error
  agent/cmd/edgemesh-agent/app/server.go
Labels: lgtm, approved, size/XS

#274 add detail log when failed to send a http request
  common/security/camanager.go
Labels: lgtm, approved, size/XS

#275 tcpproxy.proto add protocol field to support multi-protocol proxy
  agent/pkg/chassis/protocol/tcp/handler.go
  agent/pkg/gateway/manager/server.go
  agent/pkg/proxy/socks5_proxy.go
  agent/pkg/tunnel/module.go
  agent/pkg/tunnel/protocol/tcp/pb/tcpproxy.pb.go
  agent/pkg/tunnel/protocol/tcp/pb/tcpproxy.proto
  agent/pkg/tunnel/protocol/tcp/tcpproxy.go
  agent/pkg/tunnel/proxy/pb/proxy.pb.go
  agent/pkg/tunnel/proxy/pb/proxy.proto
  agent/pkg/tunnel/proxy/proxy.go
Labels: lgtm, approved, size/XXL

#280 update docs
  docs/guide/getting-started.md
  docs/guide/security.md
  docs/zh/guide/getting-started.md
  docs/zh/guide/security.md
Labels: lgtm, approved, size/M

#283 add transport docs
  docs/reference/config-items.md
  docs/zh/reference/config-items.md
Labels: lgtm, approved, size/XS
