Repository kubeedge/edgemesh, pull requests merged in 2022-09, with the labels that each got.

#362 [OSPP] Proposal for EdgeMesh supports high availability architecture Design and Implementation
  docs/proposal/edgemesh-ha-design-proposal.md
  docs/proposal/images/mesh-feature-ha/case1.svg
  docs/proposal/images/mesh-feature-ha/case2.svg
  docs/proposal/images/mesh-feature-ha/case_one.svg
  docs/proposal/images/mesh-feature-ha/case_three.svg
  docs/proposal/images/mesh-feature-ha/case_two.svg
  docs/proposal/images/mesh-feature-ha/code.svg
Labels: lgtm, approved, size/XXL

#375 fix outdate url in docs
  docs/guide/README.md
  docs/reference/config-items.md
  docs/zh/guide/README.md
  docs/zh/reference/config-items.md
Labels: lgtm, approved, size/XS

#376 update edgemesh architecture picture and modify readme
  README.md
  docs/.vuepress/public/images/em-arch.png
Labels: lgtm, approved, size/XS

#377 do not filter services that kube-proxy intends to ignore
  pkg/proxy/server.go
  vendor/k8s.io/kubernetes/pkg/proxy/apis/well_known_labels.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#378 add kubeAPIConfig and commonConfig helm configures in docs
  docs/reference/config-items.md
  docs/zh/reference/config-items.md
Labels: size/M

#380 support metaServer security feature
  cmd/edgemesh-agent/app/server.go
  cmd/edgemesh-gateway/app/server.go
  pkg/apis/config/defaults/default.go
  pkg/apis/config/v1alpha1/default.go
  pkg/apis/config/v1alpha1/types.go
  pkg/dns/corefile.go
  pkg/util/util.go
Labels: size/L

#381 update docs and helm charts
  build/helm/edgemesh-gateway.tgz
  build/helm/edgemesh-gateway/templates/04-configmap.yaml
  build/helm/edgemesh.tgz
  build/helm/edgemesh/charts/agent/templates/04-configmap.yaml
  docs/guide/README.md
  docs/reference/config-items.md
  docs/zh/guide/README.md
  docs/zh/reference/config-items.md
Labels: size/L

#382 adapt the new meaning of the requireAuthorization field of metaServer
  build/helm/edgemesh-gateway.tgz
  build/helm/edgemesh-gateway/templates/04-configmap.yaml
  build/helm/edgemesh.tgz
  build/helm/edgemesh/charts/agent/templates/04-configmap.yaml
  cmd/edgemesh-agent/app/server.go
  cmd/edgemesh-gateway/app/server.go
  pkg/apis/config/defaults/default.go
  pkg/apis/config/v1alpha1/default.go
  pkg/apis/config/v1alpha1/types.go
  pkg/util/util.go
Labels: size/L

#383 update default metaServer cert files name
  build/helm/edgemesh-gateway.tgz
  build/helm/edgemesh-gateway/templates/05-deployment.yaml
  build/helm/edgemesh-gateway/values.yaml
  build/helm/edgemesh.tgz
  build/helm/edgemesh/charts/agent/templates/05-daemonset.yaml
  build/helm/edgemesh/values.yaml
  pkg/apis/config/defaults/default.go
  pkg/apis/config/v1alpha1/types.go
  pkg/util/util.go
Labels: size/M
