Repository kubeedge/edgemesh, pull requests merged in 2023-07, with the labels that each got.

#479 slice length fix
  pkg/loadbalancer/hashring.go
Labels: lgtm, approved

#478 IPv4Mask instead the number 4
  pkg/gateway/util.go
Labels: lgtm, approved

#482 May use helm to install cloudcore,edge-kube-api.md modified
  docs/guide/edge-kube-api.md
  docs/zh/guide/edge-kube-api.md
Labels: lgtm, approved, size/S, kind/documentation

#483 update image tag to v1.14.0
  build/agent/resources/05-daemonset.yaml
  build/gateway/resources/05-deployment.yaml
  build/helm/edgemesh-gateway.tgz
  build/helm/edgemesh-gateway/values.yaml
  build/helm/edgemesh.tgz
  build/helm/edgemesh/values.yaml
Labels: size/XS

#484 Support get defaultEdgeMeshAgentMinConfig
  cmd/edgemesh-agent/app/server.go
  pkg/apis/config/v1alpha1/default.go
Labels: kind/feature, lgtm, approved, size/S
