Repository kubeedge/edgemesh, pull requests merged in 2023-02, with the labels that each got.

#424 update readme
  README.md
  README_zh.md
Labels: size/XS

#425 update readme arch image
  README.md
  README_zh.md
  docs/.vuepress/public/images/arch.png
  docs/.vuepress/public/images/arch_before1.12.png
Labels: lgtm, approved, size/XS

#430 add tunnel module comments
  pkg/tunnel/tunnel.go
Labels: lgtm, approved, size/S, kind/documentation

#431 fix tunnel tryDialEndpoint constant usage errors
  pkg/tunnel/tunnel.go
Labels: kind/bug, lgtm, approved, size/XS

#429 add omitempty json annotation
  pkg/apis/config/v1alpha1/default.go
  pkg/apis/config/v1alpha1/types.go
  pkg/apis/config/v1alpha1/validation/validation.go
  vendor/github.com/kubeedge/kubeedge/pkg/apis/componentconfig/cloudcore/v1alpha1/default.go
  vendor/github.com/kubeedge/kubeedge/pkg/apis/componentconfig/cloudcore/v1alpha1/helper.go
  vendor/github.com/kubeedge/kubeedge/pkg/apis/componentconfig/cloudcore/v1alpha1/register.go
  vendor/github.com/kubeedge/kubeedge/pkg/apis/componentconfig/cloudcore/v1alpha1/types.go
  vendor/github.com/kubeedge/kubeedge/pkg/apis/componentconfig/cloudcore/v1alpha1/validation/validation.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#433 configure ForceReachabilityPrivate when relayMap does not contain public IP
  pkg/tunnel/module.go
  pkg/tunnel/tunnel.go
Labels: size/M

#434 Relay nodes must run normally, so circuit address should be set to permanent
  pkg/tunnel/tunnel.go
  pkg/util/net/conn.go
Labels: lgtm, approved, size/S

#435 connect first during peer discovery
  pkg/tunnel/tunnel.go
Labels: size/XS

#436 add fs watcher to monitor and reload config
  cmd/edgemesh-agent/app/options/options.go
  cmd/edgemesh-agent/app/server.go
  cmd/edgemesh-gateway/app/options/options.go
  cmd/edgemesh-gateway/app/server.go
  go.mod
  pkg/apis/config/v1alpha1/default.go
  pkg/apis/config/v1alpha1/types.go
  pkg/tunnel/module.go
  pkg/tunnel/tunnel.go
  vendor/modules.txt
Labels: size/L

#437 return err when yaml.Marshal failed
  pkg/util/util.go
Labels: lgtm, approved, size/XS

#438 expose DetectRunningMode function
  pkg/apis/config/v1alpha1/default.go
Labels: size/XS
