Repository kubeedge/edgemesh, pull requests merged in 2023-06, with the labels that each got.

#477 Fix Install Go CI error
  .github/workflows/docs.yml
  .github/workflows/main.yaml
  .github/workflows/release-helm-package.yaml
Labels: kind/bug, lgtm, approved, size/M

#473 Optimization configfile path constant definition
  cmd/edgemesh-agent/app/options/options.go
  cmd/edgemesh-gateway/app/options/options.go
  pkg/apis/config/defaults/default.go
Labels: lgtm, approved, kind/cleanup, size/S

#474 specifies slice length
  pkg/loadbalancer/hashring.go
Labels: lgtm, approved, kind/cleanup, size/XS

#475 update handle error
  pkg/tunnel/tunnel.go
Labels: lgtm, approved, kind/cleanup, size/XS
