Repository kubeedge/edgemesh, pull requests merged in 2023-10, with the labels that each got.

#502 Fix kubeEdge dependencies link error
  docs/zh/guide/README.md
Labels: lgtm, approved, kind/documentation, size/XS

#511 Peer ID that distinguishes agent and gateway
  pkg/tunnel/module.go
Labels: size/XS

#510 [proposal-file] Edgemesh Container Network supports CNI features
  docs/proposal/edgemesh-cni-proposal-cn.md
  docs/proposal/edgemesh-cni-proposal-en.md
  docs/proposal/images/mesh-feature-cni/edgemesh-cni_bridge
  docs/proposal/images/mesh-feature-cni/edgemesh-cni_bridge1.png
  docs/proposal/images/mesh-feature-cni/edgemesh-cni_ipam.png
  docs/proposal/images/mesh-feature-cni/edgemesh-cni_iptableslogic.png
  docs/proposal/images/mesh-feature-cni/edgemesh-cni_logic.png
  docs/proposal/images/mesh-feature-cni/edgemesh_arch.png
  docs/proposal/images/mesh-feature-cni/edgemeshp2p.png
  docs/proposal/images/mesh-feature-cni/kubeedge_arch.png
Labels: lgtm, approved, size/XXL, kind/documentation
