Repository kubeedge/edgemesh, pull requests merged in 2023-11, with the labels that each got.

#514 The nodeName of edgemesh-gateway is added with a -gateway suffix
  cmd/edgemesh-gateway/app/server.go
  pkg/tunnel/module.go
Labels: size/XS

#513 add helm for cni
  build/helm/edgemesh.tgz
  build/helm/edgemesh/charts/agent/templates/02-clusterrole.yaml
  build/helm/edgemesh/charts/agent/templates/04-configmap.yaml
  build/helm/edgemesh/values.yaml
Labels: kind/feature, lgtm, approved, size/S

#515 optimize CNI logs and codes
  pkg/cni/adapter.go
  pkg/util/tunutils/tun.go
Labels: lgtm, approved, kind/cleanup, size/L

#518 update cni proposal
  docs/proposal/edgemesh-cni-proposal-cn.md
  docs/proposal/edgemesh-cni-proposal-en.md
Labels: lgtm, approved, kind/documentation, size/XS

#524 fix gateway serviceMap numbers sync error
  go.mod
  pkg/loadbalancer/loadbalancer.go
Labels: size/L

#528 add detail on the err log
  pkg/loadbalancer/loadbalancer.go
Labels: lgtm, approved, size/XS
