Repository kubeedge/edgemesh, pull requests merged in 2023-03, with the labels that each got.

#440 add DeleteKubeConfig field in KubeAPIConfig
  build/helm/edgemesh-gateway.tgz
  build/helm/edgemesh-gateway/templates/04-configmap.yaml
  build/helm/edgemesh.tgz
  build/helm/edgemesh/charts/agent/templates/04-configmap.yaml
  cmd/edgemesh-agent/app/server.go
  cmd/edgemesh-gateway/app/server.go
  docs/reference/config-items.md
  docs/zh/reference/config-items.md
  pkg/apis/config/defaults/default.go
  pkg/apis/config/v1alpha1/default.go
  pkg/apis/config/v1alpha1/types.go
  pkg/dns/dns.go
  pkg/util/util.go
Labels: size/M

#441 add module wrapper for shutdown beehive.core.Module
  cmd/edgemesh-agent/app/server.go
  cmd/edgemesh-gateway/app/server.go
  pkg/apis/module/module.go
  pkg/dns/module.go
  pkg/gateway/module.go
  pkg/proxy/module.go
  pkg/proxy/proxy.go
  pkg/tunnel/module.go
Labels: size/M

#442 update image tag to v1.13.1
  build/agent/resources/05-daemonset.yaml
  build/gateway/resources/05-deployment.yaml
  build/helm/edgemesh-gateway.tgz
  build/helm/edgemesh-gateway/values.yaml
  build/helm/edgemesh.tgz
  build/helm/edgemesh/values.yaml
Labels: size/XS

#445 pass cliReq to the Pick method of the loadBalancer-ConsistentHashPolicy
  cmd/edgemesh-gateway/app/server.go
  pkg/gateway/http.go
  pkg/gateway/tcp.go
  pkg/loadbalancer/loadbalancer.go
  pkg/loadbalancer/policy.go
  pkg/proxy/proxysocket.go
Labels: size/M

#448 update TempKubeConfigPath and move corefilePath to default.go
  pkg/apis/config/defaults/default.go
  pkg/dns/corefile.go
Labels: size/XS

#450 add listenInterfaces field to support tunnel service listening to the specified interfaces
  pkg/apis/config/v1alpha1/default.go
  pkg/apis/config/v1alpha1/types.go
  pkg/tunnel/module.go
  pkg/tunnel/util.go
  pkg/tunnel/util_test.go
Labels: size/L

#452 bug fix: cliReq is correctly written to outConn when the gateway requests
  pkg/loadbalancer/loadbalancer.go
  pkg/loadbalancer/policy.go
Labels: size/S

#454 fix the logical error,use continue instead return
  pkg/gateway/http.go
  pkg/gateway/util.go
Labels: lgtm, approved, size/XS

#457 Optimize code comments and code logs
  pkg/dns/corefile.go
  pkg/dns/module.go
  pkg/gateway/module.go
  pkg/proxy/module.go
  pkg/tunnel/module.go
Labels: lgtm, approved, size/S
