Repository kubeedge/edgemesh, pull requests merged in 2023-08, with the labels that each got.

#491 delete ip.String()
  pkg/gateway/gateway.go
Labels: lgtm, approved, size/XS

#493 Refine the words of the proposal.
  docs/proposal/edgemesh-ha-design-proposal.md
  docs/proposal/images/mesh-feature-ha/case1.svg
Labels: lgtm, approved, size/XL

#489 add pprof for agent and gateway
  cmd/edgemesh-agent/app/server.go
  cmd/edgemesh-gateway/app/server.go
  pkg/apis/config/v1alpha1/types.go
  pkg/profile/profile.go
Labels: kind/feature, lgtm, approved, size/M
