Repository kubeedge/edgemesh, pull requests merged in 2023-04, with the labels that each got.

#458 Update edge-kube-api.md
  docs/guide/edge-kube-api.md
Labels: lgtm, approved, size/XS

#460 feature: add extraFilteredInterfaces configuration
  build/helm/edgemesh-gateway.tgz
  build/helm/edgemesh-gateway/templates/04-configmap.yaml
  build/helm/edgemesh.tgz
  build/helm/edgemesh/charts/agent/templates/04-configmap.yaml
  pkg/apis/config/v1alpha1/types.go
  pkg/tunnel/module.go
  pkg/tunnel/util.go
  pkg/tunnel/util_test.go
Labels: lgtm, approved, size/L

#462 add const for go file
  pkg/proxy/socks5_proxy.go
Labels: lgtm, approved, size/XS

#461 docs: typo fixes
  docs/proposal/edgemesh-ha-design-proposal.md
Labels: lgtm, approved, size/S
