Repository kubeedge/edgemesh, pull requests merged in 2024-02, with the labels that each got.

#526 Add init cni process
  build/cni/Dockerfile
  build/cni/init-cni.sh
  build/helm/edgemesh.tgz
  build/helm/edgemesh/charts/spiderpool/.relok8s-images.yaml
  build/helm/edgemesh/charts/spiderpool/Chart.yaml
  build/helm/edgemesh/charts/spiderpool/README.md
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/.helmignore
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/Chart.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/LICENSE
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/README.md
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/crds/k8s.cni.cncf.io_networkattachmentdefinitions_crd.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/crds/spiderpool.spidernet.io_spidercoordinators.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/crds/spiderpool.spidernet.io_spiderendpoints.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/crds/spiderpool.spidernet.io_spiderippools.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/crds/spiderpool.spidernet.io_spiderreservedips.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/crds/spiderpool.spidernet.io_spidersubnets.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/crds/sriovnetwork.openshift.io_sriovibnetworks.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/crds/sriovnetwork.openshift.io_sriovnetworknodepolicies.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/crds/sriovnetwork.openshift.io_sriovnetworknodestates.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/crds/sriovnetwork.openshift.io_sriovnetworkpoolconfigs.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/crds/sriovnetwork.openshift.io_sriovnetworks.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/crds/sriovnetwork.openshift.io_sriovoperatorconfigs.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/templates/NOTES.txt
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/templates/_helpers.tpl
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/templates/configmap.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/templates/daemonset.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/templates/deployment.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/templates/grafanaDashboard.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/templates/pdb.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/templates/pod.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/templates/prometheusrule.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/templates/rdma-shared-dp/rdma-shared-dp.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/templates/role.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/templates/role_binding.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/templates/service.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/templates/serviceaccount.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/templates/servicemonitor.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/templates/sriov-network-operator/clusterrole.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/templates/sriov-network-operator/clusterrolebinding.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/templates/sriov-network-operator/configmap.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/templates/sriov-network-operator/operator.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/templates/sriov-network-operator/role.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/templates/sriov-network-operator/rolebinding.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/templates/sriov-network-operator/serviceaccount.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/templates/tls.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/values.yaml
  build/helm/edgemesh/charts/spiderpool/values.schema.json
  build/helm/edgemesh/charts/spiderpool/values.yaml
  build/helm/edgemesh/values.yaml
Labels: kind/feature, lgtm, approved, size/XXL

#544 update gateway cni helm
  build/helm/edgemesh-gateway.tgz
  build/helm/edgemesh-gateway/README.md
Labels: lgtm, approved, kind/documentation, size/XS

#531 optimize the cni proposal document
  docs/proposal/edgemesh-cni-proposal-cn.md
Labels: lgtm, approved, kind/cleanup, size/S

#542 add spiderpool helm charts
  Makefile
  build/helm/edgemesh.tgz
  build/helm/edgemesh/Chart.yaml
  build/helm/edgemesh/charts/spiderpool/.helmignore
  build/helm/edgemesh/charts/spiderpool/.relok8s-images.yaml
  build/helm/edgemesh/charts/spiderpool/Chart.yaml
  build/helm/edgemesh/charts/spiderpool/LICENSE
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/Chart.yaml
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/README.md
  build/helm/edgemesh/charts/spiderpool/charts/spiderpool/values.yaml
  build/helm/edgemesh/charts/spiderpool/crds/k8s.cni.cncf.io_networkattachmentdefinitions_crd.yaml
  build/helm/edgemesh/charts/spiderpool/crds/spiderpool.spidernet.io_spidercoordinators.yaml
  build/helm/edgemesh/charts/spiderpool/crds/spiderpool.spidernet.io_spiderendpoints.yaml
  build/helm/edgemesh/charts/spiderpool/crds/spiderpool.spidernet.io_spiderippools.yaml
  build/helm/edgemesh/charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  build/helm/edgemesh/charts/spiderpool/crds/spiderpool.spidernet.io_spiderreservedips.yaml
  build/helm/edgemesh/charts/spiderpool/crds/spiderpool.spidernet.io_spidersubnets.yaml
  build/helm/edgemesh/charts/spiderpool/crds/sriovnetwork.openshift.io_sriovibnetworks.yaml
  build/helm/edgemesh/charts/spiderpool/crds/sriovnetwork.openshift.io_sriovnetworknodepolicies.yaml
  build/helm/edgemesh/charts/spiderpool/crds/sriovnetwork.openshift.io_sriovnetworknodestates.yaml
  build/helm/edgemesh/charts/spiderpool/crds/sriovnetwork.openshift.io_sriovnetworkpoolconfigs.yaml
  build/helm/edgemesh/charts/spiderpool/crds/sriovnetwork.openshift.io_sriovnetworks.yaml
  build/helm/edgemesh/charts/spiderpool/crds/sriovnetwork.openshift.io_sriovoperatorconfigs.yaml
  build/helm/edgemesh/charts/spiderpool/templates/NOTES.txt
  build/helm/edgemesh/charts/spiderpool/templates/_helpers.tpl
  build/helm/edgemesh/charts/spiderpool/templates/configmap.yaml
  build/helm/edgemesh/charts/spiderpool/templates/daemonset.yaml
  build/helm/edgemesh/charts/spiderpool/templates/deployment.yaml
  build/helm/edgemesh/charts/spiderpool/templates/grafanaDashboard.yaml
  build/helm/edgemesh/charts/spiderpool/templates/pdb.yaml
  build/helm/edgemesh/charts/spiderpool/templates/pod.yaml
  build/helm/edgemesh/charts/spiderpool/templates/prometheusrule.yaml
  build/helm/edgemesh/charts/spiderpool/templates/rdma-shared-dp/rdma-shared-dp.yaml
  build/helm/edgemesh/charts/spiderpool/templates/role.yaml
  build/helm/edgemesh/charts/spiderpool/templates/role_binding.yaml
  build/helm/edgemesh/charts/spiderpool/templates/service.yaml
  build/helm/edgemesh/charts/spiderpool/templates/serviceaccount.yaml
  build/helm/edgemesh/charts/spiderpool/templates/servicemonitor.yaml
  build/helm/edgemesh/charts/spiderpool/templates/sriov-network-operator/clusterrole.yaml
  build/helm/edgemesh/charts/spiderpool/templates/sriov-network-operator/clusterrolebinding.yaml
  build/helm/edgemesh/charts/spiderpool/templates/sriov-network-operator/configmap.yaml
  build/helm/edgemesh/charts/spiderpool/templates/sriov-network-operator/operator.yaml
  build/helm/edgemesh/charts/spiderpool/templates/sriov-network-operator/role.yaml
  build/helm/edgemesh/charts/spiderpool/templates/sriov-network-operator/rolebinding.yaml
  build/helm/edgemesh/charts/spiderpool/templates/sriov-network-operator/serviceaccount.yaml
  build/helm/edgemesh/charts/spiderpool/templates/tls.yaml
  build/helm/edgemesh/charts/spiderpool/values.schema.json
  build/helm/edgemesh/charts/spiderpool/values.yaml
  build/helm/edgemesh/values.yaml
  hack/update-spiderpool-charts.sh
Labels: lgtm, approved, size/XXL

#545 update readme
  README.md
  README_zh.md
Labels: size/XS
